### ISSUE TITLE
Model Weight

### ISSUE THREAD

**Issue by anotherras** [ccr-cheng/InfGCN-pytorch#1]
Dear sir,
I am interested in experimenting with the model trained in your project. Would it be possible for you to share the weights of the model? This would be immensely helpful for my work. Thanks.

**Comment by ccr-cheng** [comment]
Thanks very much for your interest in our work! I have updated the readme to include a link to our pre-trained model. A sample electron density file is also included for testing. Follow the instructions in `inference.ipynb` to test with the pre-train model.

Chaoran
