### ISSUE TITLE
Typo in the ReadMe

### ISSUE THREAD

**Issue by seongsukim-ml** [ccr-cheng/InfGCN-pytorch#2]
Hello, I am interested in your works and try to reproduce your project but I found some typo in ReadMe.

https://github.com/ccr-cheng/InfGCN-pytorch/blame/dfe402bd2798c7482a75e3e89686c0987be427db/README.md#L71

https://github.com/ccr-cheng/InfGCN-pytorch/blame/dfe402bd2798c7482a75e3e89686c0987be427db/README.md#L79

In the training and evaluation command code, I think `main.py` is missing

Change
```
python configs/qm9.yml --savename test
```

to

```
python main.py configs/qm9.yml --savename test
```
may help.

Thank you.

**Comment by ccr-cheng** [comment]
Thank you very much for pointing this out! I have fixed this typo in the readme.

Chaoran
